api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.urlpatterns import format_suffix_patterns
from api.views import MemberListView, MemberView, \
                      KidListView, KidView, \
                      FriendshipsListView, FriendshipView, \
                      MessageListView, MessageView, MessagePostView, \
                      NotificationListView

urlpatterns = patterns('',

    url(r'^$', 'api.views.api_root'),
    url(r'^members/$', MemberListView.as_view(), name='members-list'),
    url(r'^members/(?P<pk>[0-9]+)/$', MemberView.as_view(), name='member-detail'),
    url(r'^kids/$', KidListView.as_view(), name='kids-list'),
    url(r'^kids/(?P<pk>[0-9]+)/$', KidView.as_view(), name='kid-detail'),
    url(r'^friendships/$', FriendshipsListView.as_view(), name='friendships-list'),
    url(r'^friendships/(?P<pk>[0-9]+)/$', FriendshipView.as_view(), name='friendship-view'),
    url(r'^messages/$', MessageListView.as_view(), name='messages-list'),
    url(r'^message/(?P<pk>[0-9]+)/$', MessageView.as_view(), name='message-detail'),
    url(r'^message/post$', MessagePostView.as_view(), name='message-add'),
    url(r'^notifications/$', NotificationListView.as_view(), name='notifications-list'),

    # include login URLs for the browseable API.
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),

)

urlpatterns = format_suffix_patterns(urlpatterns)

mumlife/backends/registration/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

    (r'^member/', include('mumlife.backends.registration.urls')),

"""


from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

from mumlife.backends.registration.views import ActivationView
from mumlife.backends.registration.views import RegistrationView


urlpatterns = patterns('',
   url(r'^activate/complete/$',
       TemplateView.as_view(template_name='registration/activation_complete.html'),
       name='registration_activation_complete'),
   # Activation keys get matched by \w+ instead of the more specific
   # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
   # that way it can return a sensible "invalid key" message instead of a
   # confusing 404.
   url(r'^activate/(?P<activation_key>\w+)/$',
       ActivationView.as_view(),
       name='registration_activate'),
   url(r'^register/$',
       RegistrationView.as_view(),
       name='registration_register'),
   url(r'^register/complete/$',
       TemplateView.as_view(template_name='registration/registration_complete.html'),
       name='registration_complete'),
   #url(r'^register/closed/$',
   #    TemplateView.as_view(template_name='registration/registration_closed.html'),
   #    name='registration_disallowed'),
)

mumlife/urls.py
# mumlife/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.auth.decorators import login_required
from mumlife.admin import site
from mumlife.models import Page
from mumlife.uploads import FileUploader
from mumlife.images import ImageRotater
#from mumlife.forms import PassResetForm

urlpatterns = patterns('',

    url(r'^$', 'mumlife.views.home'),
    url(Page.REGEX(), 'mumlife.views.page'),
    url(r'^local/$', 'mumlife.views.feed'),
    url(r'^events/(?P<tagstring>.*)', 'mumlife.views.events'),
    url(r'^messages/$', 'mumlife.views.messages'),
    url(r'^notifications', 'mumlife.views.notifications'),

    url(r'^write$', 'mumlife.views.write'),
    url(r'^post$', 'mumlife.views.post'),
    url(r'^post-event$', 'mumlife.views.post_event'),
    url(r'^edit-event/(?P<event_id>[0-9]+)/$', 'mumlife.views.edit_event'),
    url(r'^delete-event/(?P<event_id>[0-9]+)/$', 'mumlife.views.delete_event'),
    url(r'^message/(?P<mid>[0-9]+)/$', 'mumlife.views.message'),
    url(r'^message/(?P<mid>[0-9]+)/(?P<eventmonth>\w{3})/(?P<eventday>\d*)/$', 'mumlife.views.message'),
    url(r'^members/$', 'mumlife.views.members'),

    url(r'^member/', include('mumlife.backends.registration.urls')),
    url(r'^member/password/reset/$', 'django.contrib.auth.views.password_reset',
        {
            'from_email': settings.EMAIL_FROM,
            #'password_reset_form': PassResetForm,
            'post_reset_redirect' : '/member/password/reset/done/'
        },
        name="password_reset"),
    url(r'^member/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    url(r'^member/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {
            'post_reset_redirect' : '/member/password/reset/complete/'
        }),
    url(r'^member/password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete'),
    url(r'^member/password/change/', 'django.contrib.auth.views.password_change',
        {
            'post_change_redirect': '/profile/edit/account'
        }),
    url(r'^logout', 'django.contrib.auth.views.logout_then_login'),

    url(r'^upload$', login_required(FileUploader())),
    url(r'^manipulate/rotate$', login_required(ImageRotater())),
    url(r'^profile/edit$', 'mumlife.views.profile_edit'),
    url(r'^profile/edit/account$', 'mumlife.views.profile_edit', {'section': 'account'}),
    url(r'^profile/edit/kids$', 'mumlife.views.profile_edit', {'section': 'kids'}),
    url(r'^profile/edit/kids/(?P<kid>[0-9]+)$', 'mumlife.views.profile_edit', {'section': 'kid'}),
    url(r'^profile/edit/interests$', 'mumlife.views.profile_edit', {'section': 'interests'}),
    url(r'^profile/edit/friends$', 'mumlife.views.profile_edit', {'section': 'friends'}),
    url(r'^profile/edit/preferences$', 'mumlife.views.profile_edit', {'section': 'preferences'}),
    url(r'^profile/$', 'mumlife.views.profile'),
    url(r'^profile/(?P<slug>.+)$', 'mumlife.views.profile'),

    # Include URLs for the REST API (v1).
    url(r'^1/', include('api.urls')),

    # Back Office
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^back-office/', include(site.urls)),
    url(r'^markitup/', include('markitup.urls'))
)

mumlife/models.py
# mumlife/models.py
import logging
import operator
import random
import re
from copy import deepcopy
from datetime import datetime, timedelta
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.encoding import force_unicode
from django.utils.html import strip_tags
from django.utils.text import Truncator
from django.utils.timesince import timesince
from tagging.fields import TagField
from tagging.models import Tag, TaggedItem
from markitup.fields import MarkupField
from dateutil.rrule import rrule, WEEKLY
from dateutil.relativedelta import relativedelta
from mumlife import utils
from geo.models import Postcode

logger = logging.getLogger('mumlife.models')
POSTCODE_AREAS = Postcode.objects.all_areas()


class Page(models.Model):
    title = models.CharField(max_length=64, unique=True)
    slug = models.CharField(max_length=64, unique=True)
    body = MarkupField()
    status = models.BooleanField("Publish Status", default=False)

    def __unicode__(self):
        return self.title
    
    @staticmethod
    def REGEX():
        """ Static pages regular expression used by the URL resolver """
        return r'^(?P<page>{})$'.format('|'.join([p['slug'] for p in Page.objects.filter(status=True).values('slug')]))


class Geocode(models.Model):
    code = models.CharField(max_length=125)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __unicode__(self):
        return '{} {}'.format(self.longitude, self.latitude)


class MemberManager(models.Manager):
    def with_distance_from(self, viewer=None, query_tags=None):
        """Return all Members, ordered by their distance from the viewer.

        Viewer has to exists, or this query doesn't make sense.
        Exclude the logged-in user, Administrators, Organisers and banned members.
        """
        if viewer is None:
            return self.all()
        if query_tags is not None:
            members = TaggedItem.objects.get_by_model(Member, query_tags)
        else:
            members = self.all()

        point = 'POINT({})'.format(viewer.geocode)
        members_ids = [m['id'] for m in members.exclude(user=viewer.user) \
                                               .exclude(user__profile__geocode__isnull=True) \
                                               .exclude(user__groups__name='Administrators') \
                                               .exclude(user__is_active=False) \
                                               .exclude(gender=Member.IS_ORGANISER) \
                                               .values('id')]
        members = members.filter(id__in=members_ids) \
                         .extra(
                                select={'distance': """ST_Distance(
                                    ST_GeographyFromText(%s),
                                    ST_GeographyFromText(CONCAT('POINT(', geocode, ')'))
                                )"""},
                                select_params=(point,),
                         ) \
                         .order_by('distance')
        return members


class Member(models.Model):
    PENDING = 0
    VERIFIED = 1
    BANNED = 2
    STATUS_CHOICES = (
        (PENDING, 'Pending'),
        (VERIFIED, 'Verified'),
        (BANNED, 'Banned'),
    )
    
    IS_MUM = 0
    IS_DAD = 1
    IS_BUMP = 2
    IS_ORGANISER = 3
    GENDER_CHOICES = (
        (IS_MUM, 'Mum'),
        (IS_DAD, 'Dad'),
        (IS_BUMP, 'Bump'),
        (IS_ORGANISER, 'Organiser'),
    )

    user = models.OneToOneField(User, related_name='profile')
    fullname = models.CharField("Full Name", max_length=64)
    slug = models.CharField("Profile Slug", max_length=255, default='', blank=True)
    postcode = models.CharField("Postcode", max_length=8, help_text='Please include the gap (space) between the outward and inward codes')
    gender = models.IntegerField("Gender", choices=GENDER_CHOICES, null=True, blank=True)
    dob = models.DateField("Date of Birth", null=True, blank=True)
    status = models.IntegerField("Verification Status", choices=STATUS_CHOICES, default=PENDING)

    # Optional
    picture = models.ImageField("Picture", upload_to='./member/%Y/%m/%d', null=True, blank=True, \
                                help_text="PNG, JPEG, or GIF; max size 2 MB. Image must be 150 x 150 pixels or larger.")
    about = models.TextField("About", null=True, blank=True)
    spouse = models.ForeignKey('self', related_name='partner', null=True, blank=True, help_text="Spouse or Partner")
    interests = TagField("Interests")
    geocode = models.CharField("Geocode", max_length=255, null=True, blank=True)
    units = models.IntegerField("Units", choices=(
        (0, 'Kilometers'),
        (1, 'Miles'),
    ), null=True, blank=True, default=1, help_text="Distance measurement units")
    max_range = models.IntegerField("Maximum Search Distance", default=5, help_text="Maximum range used by the Event Calendar slider")
    friendships = models.ManyToManyField('self', null=True, blank=True, through='Friendships', \
                                         symmetrical=False, related_name='friends_with+')

    objects = MemberManager()

    def save(self, *args, **kwargs):
        if self.id is not None:
            # The profile is created after user creation,
            # therefore no data will be associated with it then.
            # It only makes sense to process data when it is updated,
            # i.e. when the data is there
            self.set_slug()
            if self.postcode:
                # Make sure the gap is there
                postcode = utils.Extractor(self.postcode.upper()).extract_postcode()
                if postcode:
                    self.postcode = postcode
                self.set_geocode()
            else:
                self.postcode = 'N/A'
        super(Member, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

    def __repr__(self):
        return u'<Member: [{}] {}>'.format(self.id, self.name)

    @property
    def is_admin(self):
        return 'Administrators' in [g['name'] for g in self.user.groups.values('name')]

    def get_distance_from(self, entity=None):
        if not entity or not entity.geocode or entity.geocode == '0.0 0.0' or \
            not self.geocode or self.geocode == '0.0 0.0':
                return {
                    'units': 'N/A',
                    'distance-display': 'N/A',
                    'distance': 99999999999
                }
        else:
            units = entity.units if hasattr(entity, 'units') else self.units
            units_display = 'Km' if units == 0 else self.get_units_display()
            distance = self.distance / 1000
            distance = distance if units == 0 else distance * 0.6214
            if round(distance, 1) < 0.5:
                units_display = 'kilometer' if units == 0 else units_display[:-1]
                distance_display = 'less than half a {}'.format(units_display.lower())
            elif round(distance, 1) <= 1.1:
                units_display = units_display if units == 0 else units_display[:-1]
                distance_display = '{} {}'.format(round(distance, 1), units_display.lower())
            else:
                distance_display = '{} {}'.format(round(distance, 1), units_display.lower())
        return {
            'units': units_display,
            'distance_display': distance_display,
            'distance': distance
        }

    def format(self, viewer=None):
        member = {}
        member['id'] = self.id
        member['is_admin'] = self.is_admin
        member['slug'] = self.slug
        member['url'] = '/profile/{}'.format(self.slug)
        member['name'] = self.get_name(viewer)
        member['age'] = self.age
        member['gender'] = self.get_gender_display()
        member['about'] = strip_tags(force_unicode(self.about)) if self.about else ''
        if viewer:
            member['friend_status'] = viewer.check_if_friend(self)
        else:
            member['friend_status'] = False
        member['area'] = self.area
        member['picture'] = self.picture.url if self.picture else ''
        # distance
        if viewer is not None:
            try:
                # The distance might have already been set by an earlier query
                # e.g. list of members includes the distance already
                # If not, this will raise an AttributeError
                _distance = self.distance
            except AttributeError:
                point_from = 'POINT({})'.format(viewer.geocode)
                point_to = 'POINT({})'.format(self.geocode)
                distance_query = Member.objects.raw("""SELECT id, ST_Distance(
                                            ST_GeographyFromText(%s),
                                            ST_GeographyFromText(%s)
                                          ) As distance
                                          FROM mumlife_member
                                          WHERE id=%s""",
                                       [point_from, point_to, self.id])
                self.distance = distance_query[0].distance
            distance = self.get_distance_from(viewer)
            member.update(distance)
        member['interests'] = self.interests.strip()
        member['kids'] = self.get_kids(viewer=viewer)
        return member

    @property
    def name(self):
        return self.get_name()

    def get_name(self, viewer=None):
        if self == viewer:
            return self.fullname
        else:
            try:
                # show lastame initials
                name = self.fullname.split()
                return '{} {}'.format(name[0], 
                                      ''.join(['{}.'.format(n[0].upper()) for n in name[1:]]))
            except IndexError:
                return 'N/A'
    
    @property
    def age(self):

mumlife/templates/page.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | {{ title }}{% endblock %}

{% block bodyclass %}staticpage{% endblock %}

{% block content %}
<div class="content">
    <div class="page">
        <h1>{{ title }}</h1>
        {{ body }}
    </div>
</div>
{% endblock %}

{% block footer %}
{% include "tags/footer.html" %}
{% endblock %}

mumlife/templates/profile_edit_account.html
{% extends "base.html" %}
{% load l10n %}

{% block bodyclass %}edit-mode edit-account{% endblock %}
{% block extrastyle %}<link type="text/css" href="{{ STATIC_URL }}css/jquery.ui.datepicker.css" rel="stylesheet" />{% endblock %}
{% block extrahead %}<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>{% endblock %}

{% block heading %}<h1>Account settings</h1>{% endblock %}

{% block content %}
    <section>

        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}

            {% if form.errors %}
                <div id="form-errors">
                    {{ form.errors }}
                </div>
            {% endif %}

            <div class="form-card box">
                <div class="form-field">
                    <label>Email Address</label>
                    <input type="email" disabled="disabled" value="{{ account.user.email }}" />
                    <p class="description">Your email address cannot be changed here. Please <a href="javascript:void(0)" data-uv-lightbox="classic_widget" data-uv-mode="full" data-uv-primary-color="#64b0b3" data-uv-link-color="#a93e2e" data-uv-default-mode="support" data-uv-forum-id="240962">contact us</a> should you wish to do so.</p>
                </div>
                <div class="form-field">
                    <label>Password</label>
                    <input type="text" disabled="disabled" value="●●●●●●●●●●" />
                    <p class="description">For security reasons, passwords are not stored, but you can it using <a href="/member/password/change/">this form</a>
                </div>
                <div class="form-field">
                    {{ form.fullname.label_tag }}
                    {{ form.fullname }}
                    <p class="description">{{ form.fullname.help_text }}</p>
                </div>
                <div class="form-field">
                    {{ form.postcode.label_tag }}
                    <input type="text" disabled="disabled" value="{{ form.postcode.value }}" />
                    <p class="description">Your postcode cannot be changed here. Please <a href="javascript:void(0)" data-uv-lightbox="classic_widget" data-uv-mode="full" data-uv-primary-color="#64b0b3" data-uv-link-color="#a93e2e" data-uv-default-mode="support" data-uv-forum-id="240962">contact us</a> should you wish to do so.</p>
                </div>
                <div class="form-field">
                    <fieldset data-role="controlgroup" id="id_gender" name="gender" data-value="{{ form.gender.value }}">
                    {% for choice in form.gender.field.choices %}
                        {% if choice.0 != '' %}
                        <input name="gender" id="gender-choice-{{ choice.0 }}" type="radio"
                               value="{{ choice.0 }}"
                               {% if choice.0 == form.gender.value %}checked="checked"{% endif %}>
                        <label for="gender-choice-{{ choice.0 }}">{{ choice.1 }}</label>
                        {% endif %}
                    {% endfor %}
                    </fieldset>
                    <p class="description">If you are an activity organiser, please select <span class="bold">Organiser</span> from the list above.</p>
                    <p class="description">You can find more information about Organisers
                        <a href="http://mumlife.uservoice.com/knowledgebase/articles/319867-activity-events-organisers" target="_blank">here</a>.</p>
                </div>
                <div class="form-field">
                    {{ form.dob.label_tag }}
                    {% localize on %}
                    <input type="date" name="dob" id="{{ form.dob.id_for_label }}"
                           value="{{ form.dob.value|date:"Y-m-d" }}"
                           placeholder="{% now "Y-m-d" %}">
                    {% endlocalize %}
                    <p class="description">Your date of birth is, and always will be, private. We won't share it with anyone.</p>
                </div>
                <div class="form-field picture">
                    {{ form.picture.label_tag }}
                    {{ form.picture }}
                    {% if form.picture.value %}
                    <div class="picture-rotate">
                        <a href="" title="Roate picture" data-entity="image-rotate">
                            <img src="{{ STATIC_URL }}img/z.gif" class="icon icon-rotate" alt="Rotate picture" />
                        </a>
                    </div>
                    {% endif %}
                    <p class="description">{{ form.picture.help_text }}</p>
                    <p class="description">The upload is known not to work on certain devices, including Windows Phones and older Android Phones.
                        You can still access your account from a computer to upload a picture.</p>
                    <p class="description"><span class="bold">You will be able to rotate the picture after it is uploaded.</span></p>
                </div>
                <div class="form-field">
                    {{ form.about.label_tag }}
                    {{ form.about }}
                    <p class="description">{{ form.about.help_text }}</p>
                </div>
            </div>

            <div class="hidden">
                {{ form.postcode }}
                {{ form.interests }}
                {{ form.units }}
                {{ form.max_range }}
            </div>
            <div data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-icon="check" data-theme="a" data-disabled="false" 
                 class="ui-submit ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-a" aria-disabled="false">
                <span class="ui-btn-inner">
                    <span class="ui-btn-text">Save</span>
                    <span class="ui-icon ui-icon-check ui-icon-shadow">&nbsp;</span>
                </span>
                <input type="submit" data-icon="check" data-role="button" value="Save" class="ui-btn-hidden" data-disabled="false">
            </div>
        </form>
    </section>
    <footer> </footer>
{% endblock %}

{% block footermenu %}
{% spaceless %}
<li>
    <a class="icon-link" href="/profile/edit" title="Back">
        <img src="{{ STATIC_URL }}img/z.gif" class="icon icon-back" alt="Back" />
    </a>
</li>
<li>
    <a class="icon-link" href="/profile" title="Profile">
        <img src="{{ STATIC_URL }}img/z.gif" class="icon icon-profile" alt="Profile" />
    </a>
</li>
{% endspaceless %}
{% endblock %}

{% block extrajs %}{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ajaxfileupload.js"></script>
<script type="text/javascript">
    $(document).on('ml.Ready', function () {
        // Mobile devices tend to have their own built-in date picker
        if (!platform.product) {
            // DoB Date Picker
            $('[name="dob"]').datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: "yy-mm-dd",
                maxDate: "-12y",
                yearRange: '1952:{% now "Y" %}',
                beforeShow: function() {
                    setTimeout(function() {
                        $('.ui-datepicker').css('z-index', 99999999999999);
                    }, 0);
                }
            });
        }

        // Expandable textareas
        $('#id_about').elastic();

        // Picture Upload Field
        new ML.Upload({'model': 'Member', 'field': 'picture', 'width': 150, 'height': 150});
        new ML.ImageRotate({'field': 'picture-edit'})
    });
</script>
<!-- UserVoice JavaScript SDK (only needed once on a page) -->
<script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/Hl3osDsDgrXWdjJCdvPwng.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>
{% endblock %}

mumlife/templates/profile_edit_kid.html
{% extends "base.html" %}
{% load l10n %}

{% block extrastyle %}<link type="text/css" href="{{ STATIC_URL }}css/jquery.ui.datepicker.css" rel="stylesheet" />{% endblock %}
{% block extrahead %}<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>{% endblock %}

{% block bodyclass %}edit-mode{% endblock %}

{% block heading %}<h1>Edit {{ kid.fullname }}</h1>{% endblock %}

{% block content %}
    <section>

        <form action="" method="post">{% csrf_token %}

            <div class="form-card box">
                <div class="form-field">
                    {{ form.fullname.label_tag }}
                    {{ form.fullname }}
                    <p class="description">{{ form.fullname.help_text }}</p>
                </div>
                <div class="form-field">
                    {{ form.gender.label_tag }}
                    <fieldset data-role="controlgroup" id="id_gender" name="gender" data-value="{{ form.gender.value }}">
                    {% for choice in form.gender.field.choices %}
                        {% if choice.0 != '' %}
                        <input name="gender" id="gender-choice-{{ choice.0 }}" type="radio"
                               value="{{ choice.0 }}"
                               {% if choice.0 == form.gender.value %}checked="checked"{% endif %}>
                        <label for="gender-choice-{{ choice.0 }}">{{ choice.1 }}</label>
                        {% endif %}
                    {% endfor %}
                    </fieldset>
                    <p class="description">{{ form.gender.help_text }}</p>
                </div>
                <div class="form-field">
                    {{ form.dob.label_tag }}
                    {% localize on %}
                    <input type="date" name="dob" id="{{ form.dob.id_for_label }}" 
                           value="{{ form.dob.value }}"
                           placeholder="{% now "Y-m-d" %}">
                    {% endlocalize %}
                    <p class="description">{{ form.dob.help_text }}</p>
                </div>
                <div class="form-field">
                    {{ form.visibility.label_tag }}
                    <fieldset data-role="controlgroup" id="id_visibility" name="visibility" data-value="{{ form.visibility.value }}">
                    {% for choice in form.visibility.field.choices %}
                        {% if choice.0 != '' %}
                        <input name="visibility" id="visibility-choice-{{ choice.0 }}" type="radio"
                               value="{{ choice.0 }}"
                               {% if choice.0 == form.visibility.value %}checked="checked"{% endif %}>
                        <label for="visibility-choice-{{ choice.0 }}">{{ choice.1 }}</label>
                        {% endif %}
                    {% endfor %}
                    </fieldset>
                    <p class="description">{{ form.visibility.help_text }}</p>
                </div>
            </div>

            <div data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-icon="check" data-theme="a" data-disabled="false"
                 class="ui-submit ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-a" aria-disabled="false">
                <span class="ui-btn-inner">
                    <span class="ui-btn-text">Save</span>
                    <span class="ui-icon ui-icon-check ui-icon-shadow">&nbsp;</span>
                </span>
                <input type="submit" data-icon="check" data-role="button" value="Save" class="ui-btn-hidden" data-disabled="false">
            </div>
        </form>
    </section>
    <footer> </footer>
{% endblock %}

{% block footermenu %}
{% spaceless %}
<li>
    <a class="icon-link" href="/profile/edit/kids" title="Back">
        <img src="{{ STATIC_URL }}img/z.gif" class="icon icon-back" alt="Back" />
    </a>
</li>
<li>
    <a class="icon-link" href="/profile" title="Profile">
        <img src="{{ STATIC_URL }}img/z.gif" class="icon icon-profile" alt="Profile" />
    </a>
</li>
{% endspaceless %}
{% endblock %}

{% block extrajs %}{{ block.super }}
<script type="text/javascript">
    $(document).on('ml.Ready', function () {
        // DoB Date Picker
        // Mobile devices tend to have their own built-in date picker
        if (!platform.product) {
            $('[name="dob"]').datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: "yy-mm-dd",
                maxDate: 0,
                yearRange: '1972:{% now "Y" %}',
                beforeShow: function() {
                    setTimeout(function() {
                        $('.ui-datepicker').css('z-index', 99999999999999);
                    }, 0);
                }
            });
        }
    });
</script>
{% endblock %}

mumlife/templates/profile_edit_preferences.html
{% extends "base.html" %}

{% block bodyclass %}edit-mode{% endblock %}

{% block heading %}<h1>Edit preferences</h1>{% endblock %}

{% block content %}
    <section>

        <div class="form-card box">
            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-field">
                    {{ form.units.label_tag }}
                    <fieldset data-role="controlgroup" id="id_units" name="units" data-value="{{ form.units.value }}">
                    {% for choice in form.units.field.choices %}
                        {% if choice.0 != '' %}
                        <input name="units" id="units-choice-{{ choice.0 }}" type="radio"
                               value="{{ choice.0 }}"
                               {% if choice.0 == form.units.value %}checked="checked"{% endif %}>
                        <label for="units-choice-{{ choice.0 }}">{{ choice.1 }}</label>
                        {% endif %}
                    {% endfor %}
                    </fieldset>
                    <p class="description">{{ form.units.help_text }}</p>
                </div>
                <div class="form-field">
                    {{ form.max_range.label_tag }}
                    {{ form.max_range }}
                    <p class="description">{{ form.max_range.help_text }}</p>
                </div>
            </form>
        </div>
        <p class="description">Changes are saved automatically.</p>

    </section>
    <footer> </footer>
{% endblock %}

{% block footermenu %}
{% spaceless %}
<li>
    <a class="icon-link" href="/profile/edit" title="Back">
        <img src="{{ STATIC_URL }}img/z.gif" class="icon icon-back" alt="Back" />
    </a>
</li>
<li>
    <a class="icon-link" href="/profile" title="Profile">
        <img src="{{ STATIC_URL }}img/z.gif" class="icon icon-profile" alt="Profile" />
    </a>
</li>
{% endspaceless %}
{% endblock %}

{% block extrajs %}{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ajaxfileupload.js"></script>
<script type="text/javascript">
    $(document).on('ml.Ready', function () {
        // Auto Fields
        new ML.AutoField({'model': 'members', 'entity': {{ account.id }}, 'field': 'units', 'widget': 'select'});
        new ML.AutoField({'model': 'members', 'entity': {{ account.id }}, 'field': 'max_range'});
    });
</script>
{% endblock %}